// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bezier-animation': string;
  'body': string;
  'collapsibleSection': string;
  'header': string;
  'headerIcon': string;
  'subSection': string;
}
export const cssExports: CssExports;
export default cssExports;
